### ISSUE TITLE
No timezone in Kiev after 2022f.15 upgrade

### ISSUE THREAD

**Issue by adrientardieu** [RomanIakovlev/timeshape#109] opened 2023-01-05 09:20 UTC
Hi,

I recently tried upgrading the timeshape library in one of my projects from `2021c.13` to `2022f.15`, but it broke a unit test I had.
Getting the timezone from coordinates `50.4501, 30.5234` used to return `[Europe/Kiev]` and it now returns `Optional.Empty`.

It does not seem normal to me.

Thanks for your feedback!

**Comment by spanasiuk** [comment] 2023-01-06 16:50
Having the same issue
Glad unit tests have caught it

**Comment by RomanIakovlev** [comment] 2023-01-14 15:54
Thanks for reporting this, I'll have a look.

**Comment by RomanIakovlev** [comment] 2023-01-15 13:07
I cannot reproduce this easily. On my computer, on the tip of the current master branch, for the given coordinates `50.4501, 30.5234` I get the `Europe/Kiev` as expected. I've run the test locally, but I don't expect this to matter, compared to downloading the build from Maven Central.

From what I've seen before, the issues with non-found time zones might be related to Java version used. I'm running on relatively old Corretto. v. 11.0.7. What's your Java versions, @spanasiuk @adrientardieu? Do you see any warnings in the logs when initializing the Timeshape?

**Comment by RomanIakovlev** [comment] 2023-01-16 09:57
After some further research, I've found out the problem is most probably related to the renaming of the timezone in question. It used to be called `Europe/Kiev`, but now it's called `Europe/Kyiv`, to harmonize with official spelling. The change has been implemented by IANA in tzdata release 2022b. 

The source data v. 2022f, from which the latest Timeshape is built, uses the updated `Europe/Kyiv` spelling, whereas the older source data v. 2021c you refer to still uses the old `Europe/Kiev` spelling. The recent JDK has both timezone IDs in its database, for compatibility reasons, but you're probably using the older Java, which doesn't yet have the `Kyiv` version.

I'm not quite sure which version of Java has introduced the updated spelling, but if you update to the latest Java minor version (e.g. 11.0.17 or 8.0.352) you should have this problem resolved.

**Comment by adrientardieu** [comment] 2023-01-18 09:48
Hello @RomanIakovlev , thanks a lot for investigating this issue. Much appreciated.
I'll try updating to the latest Java minor version because I'm still running on corretto `11.0.16`. Thanks a lot!

**Comment by An1s9n** [comment] 2023-02-12 13:38
Looks like it's not only Kyiv's problem: entire Ukraine seems to return empty `Optional` (I'm playing around with version `2022g.16`). Dripro, Zaporizhzhya, Kharkiv, Uzhgorod, Melitopol - everything returns empty `Optional`, but when I try the closest neighborhood - everything is just fine.

**Comment by An1s9n** [comment] 2023-02-12 19:21
Hi! I've run into the same problem. I was running my service on `17.0.1` JDK version and updating to `17.0.6` fixed the problem, so it is really old JDK version who causes the problem. I suppose that this issue may be closed :)

**Comment by RomanIakovlev** [comment] 2023-10-27 07:51
This issue has been opened for a long time without activity. Closing this now, feel free to re-open if you run into the same problem and the suggested solution doesn't work for you.

**Closed by RomanIakovlev** 2023-10-27 07:51 UTC
