### ISSUE TITLE
Mention zstd-jni dependency

### ISSUE THREAD

**Issue by ben-manes** [RomanIakovlev/timeshape#30] opened 2018-12-20 03:43 UTC
It wasn't obvious to me what was causing this failure at first,
```
java.lang.NoClassDefFoundError: com/github/luben/zstd/ZstdInputStream
    at net.iakovlev.timeshape.TimeZoneEngine.initialize(TimeZoneEngine.java:129)
    at net.iakovlev.timeshape.TimeZoneEngine.initialize(TimeZoneEngine.java:116)
```

I eventually realized it was due to `zstd-jni` not resolving to a platform-specific dependency. Gradle will not resolve this classifier for you, so I added the following to my build to fix the issue:

```gradle
"com.github.luben:zstd-jni:${versions.zstd}-3:${env.os.equals('macosx') ? 'darwin_x86_64' : (env.os + '_amd64')}",
```
where `env.os` was already defined as 
```gradle
env = [
  os: System.getProperty('os.name').replaceAll(' ', '').toLowerCase(),
]
```

**Comment by RomanIakovlev** [comment] 2018-12-21 12:38
Hi, thanks for reporting this! I'm not sure why Gradle behaves in such a way, but I'll try to reproduce it with build system other than sbt and see if it works.

**Comment by RomanIakovlev** [comment] 2019-10-27 14:57
I've finally come around to check what's going on with this issue, and it seems I cannot reproduce it. I've created a new Gradle project (using Gradle 5.2.1), so that my `build.gradle.kts` file looks like this:
```
plugins {
    java
}

group = "net.iakovlev"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    testCompile("junit", "junit", "4.12")
    compile("net.iakovlev", "timeshape", "2019b.7")
}

configure<JavaPluginConvention> {
    sourceCompatibility = JavaVersion.VERSION_1_8
}
```
And then in the main method I initialize Timeshape and make a call to it:
```
import net.iakovlev.timeshape.TimeZoneEngine;

import java.time.ZoneId;
import java.util.Optional;

public class Main {
    public static void main(String[] args) {
        TimeZoneEngine engine = TimeZoneEngine.initialize();
        final Optional<ZoneId> query = engine.query(51.12, 13.41);
        System.out.println(query);
    }
}
```
I ran it on Windows and Linux (WSL, Ubuntu Xenial), and it works in both cases. I see you have done it on Mac, so maybe there's something going on there, but I can't test on Mac easily.

I'd appreciate if you'd be able to have another look at the issue. Maybe it's caused by something else, not Timeshape configuration? It you still encounter this problem with Timeshape 2019b.7, it would be great to have a minimal reproducible build.

**Comment by ben-manes** [comment] 2019-10-27 18:32
Sorry, but I haven't thought much about this in almost a year. Going back to that commit, it seems that I was on Gradle 5.0. Can you check against that version to see if maybe Gradle added support as it seemed to be their issue?

When I run `./gradlew dependencies` with and without my added dependency, the output looks identical.

Removing the addition and running the server, it seems to work nicely.
```
INFO  [2019-10-27 18:31:12,967] [net.iakovlev.timeshape.Index] Initialized index with 439 time zones
```

So I think this can be closed as won't fix as Gradle must have added support?

**Comment by RomanIakovlev** [comment] 2019-10-27 19:06
Thanks a lot for your quick reply! I've tested on Gradle 5.0 as well, and it also worked with my simple example. Maybe some Heisenbug? Anyway, closing this issue now, and, if this happens again, please feel free to open another one.

**Closed by RomanIakovlev** 2019-10-27 19:06 UTC
Labels: bug
